# Download/Import PACKAGES

In [ ]:
# @title
!pip install numpy

In [8]:
def productExceptSelf( nums):
      result = 0

      copyArray = nums
      multiple  = 1;

      for i in copyArray:
          multiple *= i
      print (multiple)
      answer = [0] * len(nums)
      print (answer)
      for i in range(len(answer)):
          answer[i] = multiple / nums[i]

      print (answer)
productExceptSelf([1,2,3,4,5])

120
[0, 0, 0, 0, 0]
[120.0, 60.0, 40.0, 30.0, 24.0]


In [ ]:
# @title
import numpy as np
import time
import random as rand
import sympy as sym

# REDUCED ROW ECHELON FORM

In [ ]:
# @title
A = sym.Matrix([[1,2,4,7,8],[6,9,4,2,0],[5,6,7,2,1],[8,9,4,3,4],[2,7,3,5,0]])
print("\nThe matrix A = ", A)

start = time.time()
RREF = A.rref()
end = time.time()

print("\n\nThe RREF of A = ", RREF)

print("\n\nTime elapse for Reduced Row Echelon calculation: ", (end - start)*1000, "milliseconds" )


The matrix A =  Matrix([[1, 2, 4, 7, 8], [6, 9, 4, 2, 0], [5, 6, 7, 2, 1], [8, 9, 4, 3, 4], [2, 7, 3, 5, 0]])


The RREF of A =  (Matrix([
[1, 0, 0, 0, 0],
[0, 1, 0, 0, 0],
[0, 0, 1, 0, 0],
[0, 0, 0, 1, 0],
[0, 0, 0, 0, 1]]), (0, 1, 2, 3, 4))


Time elapse for Reduced Row Echelon calculation:  1.5997886657714844 milliseconds


# POLYNOMIAL MULTIPLICATION

In [ ]:
# @title
def list_mult(list1,list2):

  # Multiplies the matrices of polynomial coefficients by FOIL
  result = np.zeros(len(list1)*2 - 1)
  for i in range(len(list1)):
    for j in range(len(list2)):
      result[i+j] += list1[i]*list2[j]
  return result

  # TEST CASES - Complete

  # Case 1 - 4th degree polynomial
  # OUTPUT FORMAT: [a,b,c,d,e] where a = a*x^4, b = b*x^3, c = c*x^2, d = d*x^1, e = x^0 * e
listx = [1,2,3]
listy=[4,5,6]
start = time.time()

list_mult(listx,listy)
end = time.time()
print("\nList 1 = ", listx,"\nList 2 = ",listy)

print("\nMultiplication Result  = ",list_mult(listx,listy))
print("\nTime elapsed to calculate a 3rd degree polynomial multiplication: ", (end - start)*1000 , "milliseconds")
# Case 2 - 13th degree polynomial

list1 = rand.sample(range(1,100),12)
print ("\n\n\n-----------------------------------------------------------------------------\n\nList 1: ",list1)
list2 = rand.sample(range(1,100),12)
print("List 2: ", list2)
start = time.time()

a = list_mult(list1,list1)
end = time.time()

print("\nMultiplication result = ",a)
print("\nTime elapsed to calculate a 12th degree polynomial multiplication: ", (end - start)*1000 , "milliseconds")



List 1 =  [1, 2, 3] 
List 2 =  [4, 5, 6]

Multiplication Result  =  [ 4. 13. 28. 27. 18.]

Time elapsed to calculate a 3rd degree polynomial multiplication:  0.1850128173828125 milliseconds



-----------------------------------------------------------------------------

List 1:  [39, 15, 88, 22, 6, 80, 65, 35, 26, 30, 92, 73]
List 2:  [17, 33, 75, 13, 93, 53, 54, 57, 98, 83, 37, 92]

Multiplication result =  [ 1521.  1170.  7089.  4356.  8872. 10292.  9010. 19024. 18074. 13100.
 21372. 25698. 29839. 25966. 13721. 21316. 26416. 17490. 10794.  9316.
 12844. 13432.  5329.]

Time elapsed to calculate a 12th degree polynomial multiplication:  0.2067089080810547 milliseconds


# IDENTITY MATRIX

In [ ]:
# @title
def identityMatrix(dimension):
  matrix = np.eye(dimension)

  return matrix

# TEST CASE - Complete
print(identityMatrix(10))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


# LIST ADDITION AND SUBTRACTION

In [ ]:
# @title
def add_lists(L1,L2):

  # Add each element from row i and column j
  return list((i + j for i,j in zip(L1,L2)))

def subtract_lists(L1,L2):
  return list((i-j for i,j in zip(L1,L2)))

# TEST CASE ADD
listx = [1,2,3]
listy=[4,5,6]

print("\nList x + List y = ", add_lists(listx,listy))

# TEST CASE SUBTRACT

print("\n\nList x - List y = ",subtract_lists(listx,listy))


List x + List y =  [5, 7, 9]


List x - List y =  [-3, -3, -3]


*FINDS DETERMINANT*

In [ ]:
# @title
def get_det(matrix):
   try:
    return np.linalg.det(matrix)
   except np.linalg.LinAlgError:
      return "\n\nA Linear Algebra Error occured: Determinants of an M x N matrix could not be calculated "

# Retrieves determinant of any N x N matrix


## TEST CASES - Complete

# Case 1 - Square Matrix
list_A = np.random.randn(3,3)

# Case 2 -  M x N matrix: Raises Math Error because a determinant of an m x n matrix isn't real
list_B = np.random.randn(4,3)
print("List A: ",list_A)
print("\n(Rows,Columns) = ",np.shape(list_A))
print("\nDeterminant: ",get_det(list_A))

print("\n\n---------------------------------------------------------------------\n\nList B: ",list_B)
print("\n(Rows,Columns) = ",np.shape(list_B))
print("\nDeterminant: ",get_det(list_B))


List A:  [[ 0.51167206 -0.40640818  0.62069578]
 [ 1.39553892 -0.37574077  0.07483005]
 [-1.39937612 -1.56868274 -0.97257487]]

(Rows,Columns) =  (3, 3)

Determinant:  -1.9471655179506664


---------------------------------------------------------------------

List B:  [[ 1.36501822 -1.08837964 -0.27629383]
 [-0.70928894 -0.10863957 -0.90171124]
 [-0.05387099  0.59579314  0.67769082]
 [ 0.76371169 -1.32025926 -1.37018139]]

(Rows,Columns) =  (4, 3)

Determinant:  

A Linear Algebra Error occured: Determinants of an M x N matrix could not be calculated 


In [ ]:
# @title
def get_eigvalues(matrix):


  return np.linalg.eigvals(matrix)
# TEST CASES - Complete

# Case 1 - simple N x N matrix
matrix = [[2,4,6],[17,3,4],[50,60,90]]
print("Eigenvalues for the test matrix: ", get_eigvalues(matrix))

Eigenvalues for the test matrix:  [96.5697034  -1.79983976  0.23013637]
