RUN 2 CELLS BELOW FIRST!!

In [ ]:
# @title
!pip install numpy

In [ ]:
# @title
import numpy as np
import time
import random as rand
import sympy as sym

# MATRIX MULTPLICATION

In [ ]:
# @title


def matrix_mult(matrix1,matrix2):
  m1 = np.array(matrix1)
  m2 = np.array(matrix2)

  return m1 @ m2

## TEST CASE
print("First matrix: \n")
n_rows = int(input("Enter number of rows: "))
n_cols = int(input("Enter number of columns: "))

arr1 = [[float(input("Enter value for row {}  and column {} : ".format(r + 1, c + 1))) for c in range(n_cols)] for r in range(n_rows)]

print("Matrix 1 =  \n",np.array(arr1))

n_rows = int(input("\n\n\n\nSecond matrix:\n\nEnter number of rows: "))
n_cols = int(input("Enter number of columns: "))

arr2 = [[float(input("Enter value for row {}  and column {} : ".format(r + 1, c + 1))) for c in range(n_cols)] for r in range(n_rows)]

print("Matrix 2 = \n",np.array(arr2))
print("\nThe multiplicative result of matrix 1 and matrix 2 = \n",matrix_mult(arr1,arr2))


First matrix: 

Enter number of rows: 2
Enter number of columns: 2
Enter value for row 1  and column 1 : -43534
Enter value for row 1  and column 2 : 5435
Enter value for row 2  and column 1 : 0.78567
Enter value for row 2  and column 2 : 3
Matrix 1 =  
 [[-4.3534e+04  5.4350e+03]
 [ 7.8567e-01  3.0000e+00]]




Second matrix:

Enter number of rows: 2
Enter number of columns: 2
Enter value for row 1  and column 1 : 4353
Enter value for row 1  and column 2 : -600064
Enter value for row 2  and column 1 : 6.9999
Enter value for row 2  and column 2 : 7.8
Matrix 2 = 
 [[ 4.35300e+03 -6.00064e+05]
 [ 6.99990e+00  7.80000e+00]]

The multiplicative result of matrix 1 and matrix 2 = 
 [[-1.89465458e+08  2.61232286e+10]
 [ 3.44102121e+03 -4.71428883e+05]]


# REDUCED ROW ECHELON FORM

In [ ]:
# @title
A = sym.Matrix([[1,2,4,7,8],
                [6,9,4,2,0],
                [5,6,7,2,1],
                [8,9,4,3,4],
                [2,7,3,5,0]])

print("\nThe matrix A = ", A)

start = time.time()
RREF = A.rref()
end = time.time()

print("\n\nThe RREF of A = ", RREF)

print("\n\nTime elapse for Reduced Row Echelon calculation: ", (end - start)*1000, "milliseconds" )


The matrix A =  Matrix([[1, 2, 4, 7, 8], [6, 9, 4, 2, 0], [5, 6, 7, 2, 1], [8, 9, 4, 3, 4], [2, 7, 3, 5, 0]])


The RREF of A =  (Matrix([
[1, 0, 0, 0, 0],
[0, 1, 0, 0, 0],
[0, 0, 1, 0, 0],
[0, 0, 0, 1, 0],
[0, 0, 0, 0, 1]]), (0, 1, 2, 3, 4))


Time elapse for Reduced Row Echelon calculation:  2.140522003173828 milliseconds


# LIST ADDITION AND SUBTRACTION

In [ ]:
# @title
def add_lists(L1,L2):

  # Add each element from row i and column j
  return np.add(L1,L2)

def subtract_lists(L1,L2):
  return np.subtract(L1,L2)

# TEST CASE ADD
print("Provide matrices to add and subtract: \n")
print("\nFirst matrix: \n")
n_rows = int(input("Enter number of rows: "))
n_cols = int(input("Enter number of columns: "))

arr1 = [[int(input("Enter value for row {}  and column {} : ".format(r + 1, c + 1))) for c in range(n_cols)] for r in range(n_rows)]

print("Matrix 1 =  \n",np.array(arr1))



n_rows = int(input("\n\nSecond matrix:\n\nEnter number of rows: "))
n_cols = int(input("Enter number of columns: "))

arr2 = [[int(input("Enter value for row {}  and column {} : ".format(r + 1, c + 1))) for c in range(n_cols)] for r in range(n_rows)]

print("Matrix 2 = \n",np.array(arr2))

print("\n\n---------------------------------------\nList 1 + List 2 = ", add_lists(arr1,arr2))
# TEST CASE SUBTRACT

print("\n\nList 1 - List 2 = ",subtract_lists(arr1,arr2))

Provide matrices to add and subtract: 


First matrix: 

Enter number of rows: 2
Enter number of columns: 1
Enter value for row 1  and column 1 : 41
Enter value for row 2  and column 1 : 2
Matrix 1 =  
 [[41]
 [ 2]]


Second matrix:

Enter number of rows: 2
Enter number of columns: 1
Enter value for row 1  and column 1 : -6
Enter value for row 2  and column 1 : -2
Matrix 2 = 
 [[-6]
 [-2]]


---------------------------------------
List 1 + List 2 =  [[35]
 [ 0]]


List 1 - List 2 =  [[47]
 [ 4]]






# DETERMINANT

In [ ]:
# @title
def get_det(matrix):
   try:
    return np.linalg.det(matrix)
   except np.linalg.LinAlgError:
      return "\n\nA LINEAR ALGEBRA ERROR OCCURED: Determinants of an M x N matrix could not be calculated "

# Retrieves determinant of any N x N matrix


## TEST CASES - Complete

# Case 1 - Square Matrix

print("\nMatrix: \n")
n_rows = int(input("Enter number of rows: "))
n_cols = int(input("Enter number of columns: "))

arr1 = [[int(input("Enter value for row {}  and column {} : ".format(r + 1, c + 1))) for c in range(n_cols)] for r in range(n_rows)]

print("\nMatrix =  \n",np.array(arr1))
list_A = np.matrix(arr1)
# [2,1,1],[1,2,1],[1,1,2]

# Case 2 -  M x N matrix: Raises Math Error because a determinant of an m x n matrix isn't real
list_B = np.random.randn(4,3)
#print("List A: ",list_A)
print("\n(Rows,Columns) = ",np.shape(list_A))
print("\nDeterminant: ",get_det(list_A))

print("\n\n---------------------------------------------------------------------\n\nList B: ",list_B)
print("\n(Rows,Columns) = ",np.shape(list_B))
print("\nDeterminant: ",get_det(list_B))



Matrix: 

Enter number of rows: 3
Enter number of columns: 3
Enter value for row 1  and column 1 : 2
Enter value for row 1  and column 2 : 1
Enter value for row 1  and column 3 : 1
Enter value for row 2  and column 1 : 1
Enter value for row 2  and column 2 : 2
Enter value for row 2  and column 3 : 1
Enter value for row 3  and column 1 : 1
Enter value for row 3  and column 2 : 1
Enter value for row 3  and column 3 : 2

Matrix =  
 [[2 1 1]
 [1 2 1]
 [1 1 2]]

(Rows,Columns) =  (3, 3)

Determinant:  4.0


---------------------------------------------------------------------

List B:  [[ 0.36128675  0.03169215  0.32280128]
 [-1.05300665 -0.21991871  0.61455083]
 [-0.60195698 -0.06693315 -1.13750534]
 [-0.26430445  3.67168109 -1.18387247]]

(Rows,Columns) =  (4, 3)

Determinant:  

A LINEAR ALGEBRA ERROR OCCURED: Determinants of an M x N matrix could not be calculated 


# EIGENVALUES


In [ ]:
# @title
def get_eigvalues(matrix):

  return np.linalg.eigvals(matrix)
# TEST CASES - Complete

# Case 1 - simple N x N matrix
print("\n\nEnter a matrix for eigenvalue calculation: ")
n_rows = int(input("\n\nEnter number of rows: "))
n_cols = int(input("\nEnter number of columns: "))

## TEST MATRIX -

## [[4,8][6,26]]

arr1 = [[float(input("Enter value for row {}  and column {} : ".format(r + 1, c + 1))) for c in range(n_cols)] for r in range(n_rows)]

print("Matrix 1 =  \n",np.array(arr1))


print("Eigenvalues for the test matrix: ", get_eigvalues(arr1))



Enter a matrix for eigenvalue calculation: 


Enter number of rows: 2

Enter number of columns: 2
Enter value for row 1  and column 1 : -0.66846
Enter value for row 1  and column 2 : 567
Enter value for row 2  and column 1 : 767
Enter value for row 2  and column 2 : 9.69


NameError: name 'np' is not defined

# POLYNOMIAL MULTIPLICATION

In [ ]:
# @title
def list_mult(list1,list2):

  # Multiplies the matrices of polynomial coefficients by FOIL
  result = np.zeros(len(list1)*2 - 1)
  for i in range(len(list1)):
    for j in range(len(list2)):
      result[i+j] += list1[i]*list2[j]
  return result

  # TEST CASES - Complete

  # Case 1 - 4th degree polynomial
  # OUTPUT FORMAT: [a,b,c,d,e] where a = a*x^4, b = b*x^3, c = c*x^2, d = d*x^1, e = x^0 * e
listx = [1,2,3]
listy=[4,5,6]
start = time.time()
list_mult(listx,listy)
end = time.time()
print("\nList 1 = ", listx,"\nList 2 = ",listy)

print("\nMultiplication Result  = ",list_mult(listx,listy))
print("\nTime elapsed to calculate a 3rd degree polynomial multiplication: ", (end - start)*1000 , "milliseconds")
# Case 2 - 13th degree polynomial

list1 = rand.sample(range(1,100),12)
print ("\n\n\n-----------------------------------------------------------------------------\n\nList 1: ",list1)
list2 = rand.sample(range(1,100),12)
print("List 2: ", list2)
start = time.time()

a = list_mult(list1,list1)
end = time.time()

print("\nMultiplication result = ",a)
print("\nTime elapsed to calculate a 12th degree polynomial multiplication: ", (end - start)*1000 , "milliseconds")



List 1 =  [1, 2, 3] 
List 2 =  [4, 5, 6]

Multiplication Result  =  [ 4. 13. 28. 27. 18.]

Time elapsed to calculate a 3rd degree polynomial multiplication:  0.08988380432128906 milliseconds



-----------------------------------------------------------------------------

List 1:  [48, 30, 32, 79, 17, 51, 81, 96, 12, 33, 95, 85]
List 2:  [24, 71, 35, 64, 12, 94, 39, 34, 55, 91, 25, 6]

Multiplication result =  [ 2304.  2880.  3972.  9504.  7396. 10972. 18165. 20026. 20443. 24564.
 32391. 29394. 33155. 38348. 31186. 20230. 30540. 32802. 19689.  8310.
 14635. 16150.  7225.]

Time elapsed to calculate a 12th degree polynomial multiplication:  0.18143653869628906 milliseconds


# IDENTITY MATRIX

In [ ]:
# @title
def identityMatrix():
  dimension = int(input("Enter a value N to build an N x N Identity matrix: "))
  matrix = np.eye(dimension)

  return matrix

# TEST CASE - Complete
print(identityMatrix())

Enter a value N to build an N x N Identity matrix: 20
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 