<a href="https://colab.research.google.com/github/VedantPatel04/Matrices_Calculator/blob/main/Matrices_Calculator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# @title
!pip install numpy

In [3]:
# @title
import numpy as np
import time
import random as rand
import sympy as sym

# MATRIX MULTPLICATION

In [5]:
# @title


def matrix_mult(matrix1,matrix2):
  m1 = np.array(matrix1)
  m2 = np.array(matrix2)

  return m1 @ m2

## TEST CASE
print("First matrix: \n")
n_rows = int(input("Enter number of rows: "))
n_cols = int(input("Enter number of columns: "))

arr1 = [[int(input("Enter value for row {}  and column {} : ".format(r + 1, c + 1))) for c in range(n_cols)] for r in range(n_rows)]

print("Matrix 1 =  \n",np.array(arr1))

n_rows = int(input("\n\n\n\nSecond matrix:\n\nEnter number of rows: "))
n_cols = int(input("Enter number of columns: "))

arr2 = [[int(input("Enter value for row {}  and column {} : ".format(r + 1, c + 1))) for c in range(n_cols)] for r in range(n_rows)]

print("Matrix 2 = \n",np.array(arr2))
print("\nThe multiplicative result of matrix 1 and matrix 2 = \n",matrix_mult(arr1,arr2))


First matrix: 

Enter number of rows: 2
Enter number of columns: 2
Enter value for row 1  and column 1 : 3
Enter value for row 1  and column 2 : 5
Enter value for row 2  and column 1 : 6
Enter value for row 2  and column 2 : 7
Matrix 1 =  
 [[3 5]
 [6 7]]




Second matrix:

Enter number of rows: 2
Enter number of columns: 2
Enter value for row 1  and column 1 : 8
Enter value for row 1  and column 2 : 7
Enter value for row 2  and column 1 : 6
Enter value for row 2  and column 2 : 5
Matrix 2 = 
 [[8 7]
 [6 5]]

The multiplicative result of matrix 1 and matrix 2 = 
 [[54 46]
 [90 77]]


# POLYNOMIAL MULTIPLICATION

In [ ]:
# @title
def list_mult(list1,list2):

  # Multiplies the matrices of polynomial coefficients by FOIL
  result = np.zeros(len(list1)*2 - 1)
  for i in range(len(list1)):
    for j in range(len(list2)):
      result[i+j] += list1[i]*list2[j]
  return result

  # TEST CASES - Complete

  # Case 1 - 4th degree polynomial
  # OUTPUT FORMAT: [a,b,c,d,e] where a = a*x^4, b = b*x^3, c = c*x^2, d = d*x^1, e = x^0 * e
listx = [1,2,3]
listy=[4,5,6]
start = time.time()

list_mult(listx,listy)
end = time.time()
print("\nList 1 = ", listx,"\nList 2 = ",listy)

print("\nMultiplication Result  = ",list_mult(listx,listy))
print("\nTime elapsed to calculate a 3rd degree polynomial multiplication: ", (end - start)*1000 , "milliseconds")
# Case 2 - 13th degree polynomial

list1 = rand.sample(range(1,100),12)
print ("\n\n\n-----------------------------------------------------------------------------\n\nList 1: ",list1)
list2 = rand.sample(range(1,100),12)
print("List 2: ", list2)
start = time.time()

a = list_mult(list1,list1)
end = time.time()

print("\nMultiplication result = ",a)
print("\nTime elapsed to calculate a 12th degree polynomial multiplication: ", (end - start)*1000 , "milliseconds")



List 1 =  [1, 2, 3] 
List 2 =  [4, 5, 6]

Multiplication Result  =  [ 4. 13. 28. 27. 18.]

Time elapsed to calculate a 3rd degree polynomial multiplication:  0.3113746643066406 milliseconds



-----------------------------------------------------------------------------

List 1:  [36, 37, 99, 79, 54, 89, 98, 78, 2, 24, 56, 46]
List 2:  [30, 35, 24, 91, 97, 39, 56, 83, 57, 62, 95, 87]

Multiplication result =  [ 1296.  2664.  8497. 13014. 19535. 26046. 30575. 39022. 42298. 42416.
 37033. 38392. 41988. 36192. 24064. 19952. 22912. 17848.  7976.  2872.
  5344.  5152.  2116.]

Time elapsed to calculate a 12th degree polynomial multiplication:  0.17404556274414062 milliseconds


# REDUCED ROW ECHELON FORM

In [5]:
# @title
A = sym.Matrix([[1,2,4,7,8],[6,9,4,2,0],[5,6,7,2,1],[8,9,4,3,4],[2,7,3,5,0]])
print("\nThe matrix A = ", A)

start = time.time()
RREF = A.rref()
end = time.time()

print("\n\nThe RREF of A = ", RREF)

print("\n\nTime elapse for Reduced Row Echelon calculation: ", (end - start)*1000, "milliseconds" )


The matrix A =  Matrix([[1, 2, 4, 7, 8], [6, 9, 4, 2, 0], [5, 6, 7, 2, 1], [8, 9, 4, 3, 4], [2, 7, 3, 5, 0]])


The RREF of A =  (Matrix([
[1, 0, 0, 0, 0],
[0, 1, 0, 0, 0],
[0, 0, 1, 0, 0],
[0, 0, 0, 1, 0],
[0, 0, 0, 0, 1]]), (0, 1, 2, 3, 4))


Time elapse for Reduced Row Echelon calculation:  2.140522003173828 milliseconds


# IDENTITY MATRIX

In [ ]:
# @title
def identityMatrix(dimension):
  matrix = np.eye(dimension)

  return matrix

# TEST CASE - Complete
print(identityMatrix(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# LIST ADDITION AND SUBTRACTION

In [ ]:
# @title
def add_lists(L1,L2):

  # Add each element from row i and column j
  return np.add(L1,L2)

def subtract_lists(L1,L2):
  return np.subtract(L1,L2)

# TEST CASE ADD
print("Provide matrices to add and subtract: \n")
print("\nFirst matrix: \n")
n_rows = int(input("Enter number of rows: "))
n_cols = int(input("Enter number of columns: "))

arr1 = [[int(input("Enter value for row {}  and column {} : ".format(r + 1, c + 1))) for c in range(n_cols)] for r in range(n_rows)]

print("Matrix 1 =  \n",np.array(arr1))



n_rows = int(input("\n\nSecond matrix:\n\nEnter number of rows: "))
n_cols = int(input("Enter number of columns: "))

arr2 = [[int(input("Enter value for row {}  and column {} : ".format(r + 1, c + 1))) for c in range(n_cols)] for r in range(n_rows)]

print("Matrix 2 = \n",np.array(arr2))

print("\n\n---------------------------------------\nList 1 + List 1 = ", add_lists(arr1,arr2))
# TEST CASE SUBTRACT

print("\n\nList 1 - List 2 = ",subtract_lists(arr1,arr2))

Provide matrices to add and subtract: 


First matrix: 

Enter number of rows: 1
Enter number of columns: 2
Enter value for row 1  and column 1 : 3
Enter value for row 1  and column 2 : 3
Matrix 1 =  
 [[3 3]]


Second matrix:

Enter number of rows: 1
Enter number of columns: 2
Enter value for row 1  and column 1 : 4
Enter value for row 1  and column 2 : 4
Matrix 2 = 
 [[4 4]]


---------------------------------------
List 1 + List 1 =  [[7 7]]


List 1 - List 2 =  [[-1 -1]]






# DETERMINANT

In [ ]:
# @title
def get_det(matrix):
   try:
    return np.linalg.det(matrix)
   except np.linalg.LinAlgError:
      return "\n\nA Linear Algebra Error occured: Determinants of an M x N matrix could not be calculated "

# Retrieves determinant of any N x N matrix


## TEST CASES - Complete

# Case 1 - Square Matrix
list_A = np.random.randn(3,3)

# Case 2 -  M x N matrix: Raises Math Error because a determinant of an m x n matrix isn't real
list_B = np.random.randn(4,3)
print("List A: ",list_A)
print("\n(Rows,Columns) = ",np.shape(list_A))
print("\nDeterminant: ",get_det(list_A))

print("\n\n---------------------------------------------------------------------\n\nList B: ",list_B)
print("\n(Rows,Columns) = ",np.shape(list_B))
print("\nDeterminant: ",get_det(list_B))


List A:  [[ 0.51167206 -0.40640818  0.62069578]
 [ 1.39553892 -0.37574077  0.07483005]
 [-1.39937612 -1.56868274 -0.97257487]]

(Rows,Columns) =  (3, 3)

Determinant:  -1.9471655179506664


---------------------------------------------------------------------

List B:  [[ 1.36501822 -1.08837964 -0.27629383]
 [-0.70928894 -0.10863957 -0.90171124]
 [-0.05387099  0.59579314  0.67769082]
 [ 0.76371169 -1.32025926 -1.37018139]]

(Rows,Columns) =  (4, 3)

Determinant:  

A Linear Algebra Error occured: Determinants of an M x N matrix could not be calculated 


# EIGENVALUES


In [ ]:
# @title
def get_eigvalues(matrix):

  return np.linalg.eigvals(matrix)
# TEST CASES - Complete

# Case 1 - simple N x N matrix
print("\n\nEnter a matrix for eigenvalue calculation: ")
n_rows = int(input("\n\nEnter number of rows: "))
n_cols = int(input("\nEnter number of columns: "))

arr1 = [[int(input("Enter value for row {}  and column {} : ".format(r + 1, c + 1))) for c in range(n_cols)] for r in range(n_rows)]

print("Matrix 1 =  \n",np.array(arr1))


print("Eigenvalues for the test matrix: ", get_eigvalues(arr1))



Enter a matrix for eigenvalue calculation: 
